// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qwddtvotgdzcswcvuqpw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InF3ZGR0dm90Z2R6Y3N3Y3Z1cXB3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTMwODY2NzEsImV4cCI6MjA2ODY2MjY3MX0.F1mpVO4qDUFSo2Y7XjWT09vGNKm1JYH_ruOOPVBAwiU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});